export const projectsData = [
  {
    slug: "openshelf",
    number: "01",
    name: "OpenShelf",
    tagline: "Online Book Borrowing Platform",
    description:
      "A full stack book borrowing platform where users can browse, borrow, and manage books online. Features Google OAuth, protected routes, and a clean library management system.",
    stack: ["Next.js", "BetterAuth", "MongoDB", "Tailwind", "DaisyUI"],
    live: "https://open-shelf-ten.vercel.app/",
    github: "https://github.com/farhansm01/OpenShelf",
    image: "/projects/openshelf.png",
    color: "#8b5cf6",
    challenges: [
      "Integrating BetterAuth was the biggest hurdle — social login with Google kept failing due to callback URL misconfigurations and OAuth scope issues that took significant debugging to resolve.",
      "Managing protected routes and session persistence across server and client components in Next.js required careful architecture decisions.",
      "Designing the book borrowing logic — handling availability status, due dates, and preventing duplicate borrows — needed multiple iterations to get right.",
    ],
    future: [
      "Build a full admin dashboard where admins can add, edit, and remove books, manage users, and view borrowing analytics.",
      "Add email notifications for due date reminders and successful borrow confirmations.",
      "Implement a book recommendation system based on borrowing history and reading preferences.",
      "Add a reviews and ratings system so users can share feedback on books they've read.",
    ],
  },
  {
    slug: "dragon-news",
    number: "02",
    name: "Dragon News",
    tagline: "Category-Based News Platform",
    description:
      "A news portal with category-based browsing, private routes, and OAuth login. Features a React Marquee ticker, dynamic category sidebar, and smooth authentication flow.",
    stack: ["Next.js", "BetterAuth", "Tailwind", "React Marquee"],
    live: "https://dragon-news-omega-lemon.vercel.app/",
    github: "https://github.com/farhansm01/Dragon-News",
    image: "/projects/dragon-news.png",
    color: "#22d3ee",
    challenges: [
      "This was one of the first projects using BetterAuth, so the learning curve was steep — understanding the auth flow, session handling, and protected routes took considerable time.",
      "Keeping the category sidebar in sync with the active news feed without unnecessary re-renders required careful state management.",
      "Making the React Marquee ticker responsive and smooth across different screen sizes was trickier than expected.",
    ],
    future: [
      "Implement a multi-role authentication system — Admin can manage all content, Editors can write and publish articles, and regular users can read and comment.",
      "Add a rich text editor for article creation so editors can format content properly.",
      "Improve the overall UI with better typography, dark/light mode, and smoother transitions.",
      "Add search functionality with filters by category, date, and author.",
    ],
  },
  {
    slug: "book-vibe",
    number: "03",
    name: "Book Vibe",
    tagline: "Smart Book Library App",
    description:
      "A book library app with Read List and Wishlist functionality powered by localStorage. Built with React 19, React Router v7, and Recharts for reading analytics.",
    stack: ["React 19", "React Router v7", "Tailwind", "DaisyUI", "Recharts"],
    live: "https://book-vibe-fsm.netlify.app/",
    github: "https://github.com/farhansm01/Book-Vibe",
    image: "/projects/book-vibe.png",
    color: "#f472b6",
    challenges: [
      "Working with React Router v7 for the first time introduced new patterns around data loading and navigation that required adjusting to a different mental model.",
      "Managing localStorage state across multiple components without a global state solution led to some sync issues that required a custom hook to resolve.",
      "Implementing Recharts for reading analytics required understanding data transformation — converting raw book lists into chart-friendly formats.",
    ],
    future: [
      "Connect to a backend with user accounts so reading lists persist across devices instead of relying on localStorage.",
      "Integrate a public books API like Google Books to allow users to search and add any book to their list.",
      "Add reading progress tracking — users can mark how many pages they've read and see progress bars.",
      "Build a social feature where users can share their reading lists and see what friends are reading.",
    ],
  },
  {
    slug: "keenkeeper",
    number: "04",
    name: "KeenKeeper",
    tagline: "Relationship Management App",
    description:
      "A personal relationship tracker with interaction timeline, analytics dashboard, and friend management. Uses Context API for state and Recharts for visual analytics.",
    stack: ["React", "React Router", "Context API", "Tailwind", "Recharts"],
    live: "https://keen-keeper-fsm.netlify.app/",
    github: "https://github.com/farhansm01/Keen-Keeper",
    image: "/projects/keen-keeper.png",
    color: "#fb923c",
    challenges: [
      "Designing the data model for tracking interactions was complex — each contact needed a timeline of different interaction types with timestamps and notes.",
      "Context API became hard to manage as the app grew — passing deeply nested state without unnecessary re-renders required careful structuring of providers.",
      "Building the analytics dashboard with Recharts required aggregating interaction data into meaningful insights which involved complex data transformation logic.",
    ],
    future: [
      "Integrate actual communication features — send messages or make calls directly from the app using Twilio or WhatsApp API to make it fully functional.",
      "Add reminders and notifications — get reminded to reach out to contacts you haven't spoken to in a while.",
      "Connect to a backend with real authentication so data persists and users can access their contacts from any device.",
      "Add import functionality to sync contacts from phone or Google Contacts.",
    ],
  },
];